name: Docker

on:
  workflow_call:

jobs:
  docker:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3.8.0

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: my-artifact-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.sha }}
          path: main
          
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          Username: ${{ secrets.DOCKERUSER }}
          Password: ${{ secrets.DOCKERKEY }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.12.0
        with:
          context: .        
          file: ./Dockerfile          
          push: true
          tags: ${{secrets.DOCKERUSER}}/go_ci:${{github.ref_name}}    
