name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:   
    runs-on: ${{ matrix.os }}
    env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      NAME: ${{ secrets.NAME }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04']
        go_version: ['1.19', '1.20', '1.21.x']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: build
      run: sudo apt-get install docker-compose -y

    - name: Create-DB
      run: docker-compose up -d postgres

    - name: Test
      run: go test -v main_test.go 
      
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
            name: programa
            path: main

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
